# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: fibonacci.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66ibonacci.proto\" \n\x0fSequenceRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x03\"1\n\x0fSequenceElement\x12\x0f\n\x07\x65lement\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"#\n\x10SequenceResponse\x12\x0f\n\x07\x65lement\x18\x01 \x03(\x03\x32\x82\x01\n\x10\x46ibonacciService\x12\x34\n\x0bGetSequence\x12\x10.SequenceRequest\x1a\x11.SequenceResponse\"\x00\x12\x38\n\x0eStreamSequence\x12\x10.SequenceRequest\x1a\x10.SequenceElement\"\x00\x30\x01\x62\x06proto3')



_SEQUENCEREQUEST = DESCRIPTOR.message_types_by_name['SequenceRequest']
_SEQUENCEELEMENT = DESCRIPTOR.message_types_by_name['SequenceElement']
_SEQUENCERESPONSE = DESCRIPTOR.message_types_by_name['SequenceResponse']
SequenceRequest = _reflection.GeneratedProtocolMessageType('SequenceRequest', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCEREQUEST,
  '__module__' : 'fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:SequenceRequest)
  })
_sym_db.RegisterMessage(SequenceRequest)

SequenceElement = _reflection.GeneratedProtocolMessageType('SequenceElement', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCEELEMENT,
  '__module__' : 'fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:SequenceElement)
  })
_sym_db.RegisterMessage(SequenceElement)

SequenceResponse = _reflection.GeneratedProtocolMessageType('SequenceResponse', (_message.Message,), {
  'DESCRIPTOR' : _SEQUENCERESPONSE,
  '__module__' : 'fibonacci_pb2'
  # @@protoc_insertion_point(class_scope:SequenceResponse)
  })
_sym_db.RegisterMessage(SequenceResponse)

_FIBONACCISERVICE = DESCRIPTOR.services_by_name['FibonacciService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SEQUENCEREQUEST._serialized_start=19
  _SEQUENCEREQUEST._serialized_end=51
  _SEQUENCEELEMENT._serialized_start=53
  _SEQUENCEELEMENT._serialized_end=102
  _SEQUENCERESPONSE._serialized_start=104
  _SEQUENCERESPONSE._serialized_end=139
  _FIBONACCISERVICE._serialized_start=142
  _FIBONACCISERVICE._serialized_end=272
# @@protoc_insertion_point(module_scope)
