# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import fibonacci_pb2 as fibonacci__pb2


class FibonacciServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSequence = channel.unary_unary(
                '/FibonacciService/GetSequence',
                request_serializer=fibonacci__pb2.SequenceRequest.SerializeToString,
                response_deserializer=fibonacci__pb2.SequenceResponse.FromString,
                )
        self.StreamSequence = channel.unary_stream(
                '/FibonacciService/StreamSequence',
                request_serializer=fibonacci__pb2.SequenceRequest.SerializeToString,
                response_deserializer=fibonacci__pb2.SequenceElement.FromString,
                )


class FibonacciServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamSequence(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FibonacciServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSequence': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSequence,
                    request_deserializer=fibonacci__pb2.SequenceRequest.FromString,
                    response_serializer=fibonacci__pb2.SequenceResponse.SerializeToString,
            ),
            'StreamSequence': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamSequence,
                    request_deserializer=fibonacci__pb2.SequenceRequest.FromString,
                    response_serializer=fibonacci__pb2.SequenceElement.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FibonacciService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FibonacciService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/FibonacciService/GetSequence',
            fibonacci__pb2.SequenceRequest.SerializeToString,
            fibonacci__pb2.SequenceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamSequence(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/FibonacciService/StreamSequence',
            fibonacci__pb2.SequenceRequest.SerializeToString,
            fibonacci__pb2.SequenceElement.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
